/**
 * Все страны и территории для анализа выдачи: код ISO alpha-2, числовой код ISO 3166-1,
 * название по-русски и по-английски, язык поиска по умолчанию.
 * DataForSEO: location_code страны = 2000 + числовой код ISO (Нидерланды 528 → 2528, Замбия 894 → 2894).
 * SerpAPI: gl = код alpha-2, hl = язык.
 */
export type Country = { code: string; numeric: number; name: string; en: string; lang: string; /** местные названия для гео-приставок */ words?: string[] };

const C = (code: string, numeric: number, name: string, en: string, lang: string, words?: string[]): Country => ({ code, numeric, name, en, lang, words });

export const COUNTRIES: Country[] = [
  C("af", 4, "Афганистан", "Afghanistan", "fa"),
  C("al", 8, "Албания", "Albania", "sq", ["shqiperia"]),
  C("dz", 12, "Алжир", "Algeria", "fr"),
  C("as", 16, "Американское Самоа", "American Samoa", "en"),
  C("ad", 20, "Андорра", "Andorra", "ca"),
  C("ao", 24, "Ангола", "Angola", "pt"),
  C("ai", 660, "Ангилья", "Anguilla", "en"),
  C("ag", 28, "Антигуа и Барбуда", "Antigua and Barbuda", "en"),
  C("ar", 32, "Аргентина", "Argentina", "es"),
  C("am", 51, "Армения", "Armenia", "hy"),
  C("aw", 533, "Аруба", "Aruba", "nl"),
  C("au", 36, "Австралия", "Australia", "en", ["aus", "oz"]),
  C("at", 40, "Австрия", "Austria", "de", ["osterreich", "oesterreich"]),
  C("az", 31, "Азербайджан", "Azerbaijan", "az"),
  C("bs", 44, "Багамы", "Bahamas", "en"),
  C("bh", 48, "Бахрейн", "Bahrain", "ar"),
  C("bd", 50, "Бангладеш", "Bangladesh", "bn"),
  C("bb", 52, "Барбадос", "Barbados", "en"),
  C("by", 112, "Беларусь", "Belarus", "ru"),
  C("be", 56, "Бельгия", "Belgium", "nl", ["belgie", "belgique", "belgien"]),
  C("bz", 84, "Белиз", "Belize", "en"),
  C("bj", 204, "Бенин", "Benin", "fr"),
  C("bm", 60, "Бермуды", "Bermuda", "en"),
  C("bt", 64, "Бутан", "Bhutan", "en"),
  C("bo", 68, "Боливия", "Bolivia", "es"),
  C("ba", 70, "Босния и Герцеговина", "Bosnia and Herzegovina", "bs", ["bosna"]),
  C("bw", 72, "Ботсвана", "Botswana", "en"),
  C("br", 76, "Бразилия", "Brazil", "pt", ["brasil"]),
  C("bn", 96, "Бруней", "Brunei", "ms"),
  C("bg", 100, "Болгария", "Bulgaria", "bg", ["balgariya"]),
  C("bf", 854, "Буркина-Фасо", "Burkina Faso", "fr"),
  C("bi", 108, "Бурунди", "Burundi", "fr"),
  C("kh", 116, "Камбоджа", "Cambodia", "km"),
  C("cm", 120, "Камерун", "Cameroon", "fr"),
  C("ca", 124, "Канада", "Canada", "en"),
  C("cv", 132, "Кабо-Верде", "Cape Verde", "pt"),
  C("ky", 136, "Каймановы острова", "Cayman Islands", "en"),
  C("cf", 140, "Центральноафриканская Республика", "Central African Republic", "fr"),
  C("td", 148, "Чад", "Chad", "fr"),
  C("cl", 152, "Чили", "Chile", "es"),
  C("cn", 156, "Китай", "China", "zh-CN"),
  C("co", 170, "Колумбия", "Colombia", "es"),
  C("km", 174, "Коморы", "Comoros", "fr"),
  C("cg", 178, "Конго", "Congo", "fr"),
  C("cd", 180, "ДР Конго", "DR Congo", "fr"),
  C("ck", 184, "Острова Кука", "Cook Islands", "en"),
  C("cr", 188, "Коста-Рика", "Costa Rica", "es"),
  C("ci", 384, "Кот-д’Ивуар", "Ivory Coast", "fr"),
  C("hr", 191, "Хорватия", "Croatia", "hr", ["hrvatska"]),
  C("cu", 192, "Куба", "Cuba", "es"),
  C("cw", 531, "Кюрасао", "Curaçao", "nl"),
  C("cy", 196, "Кипр", "Cyprus", "el", ["kypros", "kibris"]),
  C("cz", 203, "Чехия", "Czechia", "cs", ["cesko", "czech"]),
  C("dk", 208, "Дания", "Denmark", "da", ["danmark"]),
  C("dj", 262, "Джибути", "Djibouti", "fr"),
  C("dm", 212, "Доминика", "Dominica", "en"),
  C("do", 214, "Доминиканская Республика", "Dominican Republic", "es"),
  C("ec", 218, "Эквадор", "Ecuador", "es"),
  C("eg", 818, "Египет", "Egypt", "ar", ["misr"]),
  C("sv", 222, "Сальвадор", "El Salvador", "es"),
  C("gq", 226, "Экваториальная Гвинея", "Equatorial Guinea", "es"),
  C("er", 232, "Эритрея", "Eritrea", "en"),
  C("ee", 233, "Эстония", "Estonia", "et", ["eesti"]),
  C("sz", 748, "Эсватини", "Eswatini", "en"),
  C("et", 231, "Эфиопия", "Ethiopia", "en"),
  C("fk", 238, "Фолклендские острова", "Falkland Islands", "en"),
  C("fo", 234, "Фарерские острова", "Faroe Islands", "fo"),
  C("fj", 242, "Фиджи", "Fiji", "en"),
  C("fi", 246, "Финляндия", "Finland", "fi", ["suomi"]),
  C("fr", 250, "Франция", "France", "fr"),
  C("gf", 254, "Французская Гвиана", "French Guiana", "fr"),
  C("pf", 258, "Французская Полинезия", "French Polynesia", "fr"),
  C("ga", 266, "Габон", "Gabon", "fr"),
  C("gm", 270, "Гамбия", "Gambia", "en"),
  C("ge", 268, "Грузия", "Georgia", "ka", ["sakartvelo"]),
  C("de", 276, "Германия", "Germany", "de", ["deutschland"]),
  C("gh", 288, "Гана", "Ghana", "en"),
  C("gi", 292, "Гибралтар", "Gibraltar", "en"),
  C("gr", 300, "Греция", "Greece", "el", ["hellas", "ellada"]),
  C("gl", 304, "Гренландия", "Greenland", "da"),
  C("gd", 308, "Гренада", "Grenada", "en"),
  C("gp", 312, "Гваделупа", "Guadeloupe", "fr"),
  C("gu", 316, "Гуам", "Guam", "en"),
  C("gt", 320, "Гватемала", "Guatemala", "es"),
  C("gg", 831, "Гернси", "Guernsey", "en"),
  C("gn", 324, "Гвинея", "Guinea", "fr"),
  C("gw", 624, "Гвинея-Бисау", "Guinea-Bissau", "pt"),
  C("gy", 328, "Гайана", "Guyana", "en"),
  C("ht", 332, "Гаити", "Haiti", "fr"),
  C("hn", 340, "Гондурас", "Honduras", "es"),
  C("hk", 344, "Гонконг", "Hong Kong", "en"),
  C("hu", 348, "Венгрия", "Hungary", "hu", ["magyar", "magyarorszag"]),
  C("is", 352, "Исландия", "Iceland", "is"),
  C("in", 356, "Индия", "India", "en", ["bharat"]),
  C("id", 360, "Индонезия", "Indonesia", "id"),
  C("ir", 364, "Иран", "Iran", "fa"),
  C("iq", 368, "Ирак", "Iraq", "ar"),
  C("ie", 372, "Ирландия", "Ireland", "en", ["eire"]),
  C("im", 833, "Остров Мэн", "Isle of Man", "en"),
  C("il", 376, "Израиль", "Israel", "he"),
  C("it", 380, "Италия", "Italy", "it", ["italia"]),
  C("jm", 388, "Ямайка", "Jamaica", "en"),
  C("jp", 392, "Япония", "Japan", "ja", ["nihon", "nippon"]),
  C("je", 832, "Джерси", "Jersey", "en"),
  C("jo", 400, "Иордания", "Jordan", "ar"),
  C("kz", 398, "Казахстан", "Kazakhstan", "ru"),
  C("ke", 404, "Кения", "Kenya", "en"),
  C("ki", 296, "Кирибати", "Kiribati", "en"),
  C("kw", 414, "Кувейт", "Kuwait", "ar"),
  C("kg", 417, "Киргизия", "Kyrgyzstan", "ru"),
  C("la", 418, "Лаос", "Laos", "lo"),
  C("lv", 428, "Латвия", "Latvia", "lv", ["latvija"]),
  C("lb", 422, "Ливан", "Lebanon", "ar"),
  C("ls", 426, "Лесото", "Lesotho", "en"),
  C("lr", 430, "Либерия", "Liberia", "en"),
  C("ly", 434, "Ливия", "Libya", "ar"),
  C("li", 438, "Лихтенштейн", "Liechtenstein", "de"),
  C("lt", 440, "Литва", "Lithuania", "lt", ["lietuva"]),
  C("lu", 442, "Люксембург", "Luxembourg", "fr"),
  C("mo", 446, "Макао", "Macao", "zh-TW"),
  C("mg", 450, "Мадагаскар", "Madagascar", "fr"),
  C("mw", 454, "Малави", "Malawi", "en"),
  C("my", 458, "Малайзия", "Malaysia", "ms"),
  C("mv", 462, "Мальдивы", "Maldives", "en"),
  C("ml", 466, "Мали", "Mali", "fr"),
  C("mt", 470, "Мальта", "Malta", "en"),
  C("mh", 584, "Маршалловы Острова", "Marshall Islands", "en"),
  C("mq", 474, "Мартиника", "Martinique", "fr"),
  C("mr", 478, "Мавритания", "Mauritania", "ar"),
  C("mu", 480, "Маврикий", "Mauritius", "en"),
  C("yt", 175, "Майотта", "Mayotte", "fr"),
  C("mx", 484, "Мексика", "Mexico", "es"),
  C("fm", 583, "Микронезия", "Micronesia", "en"),
  C("md", 498, "Молдова", "Moldova", "ro"),
  C("mc", 492, "Монако", "Monaco", "fr"),
  C("mn", 496, "Монголия", "Mongolia", "mn"),
  C("me", 499, "Черногория", "Montenegro", "sr", ["crnagora"]),
  C("ms", 500, "Монтсеррат", "Montserrat", "en"),
  C("ma", 504, "Марокко", "Morocco", "fr", ["maroc"]),
  C("mz", 508, "Мозамбик", "Mozambique", "pt"),
  C("mm", 104, "Мьянма", "Myanmar", "my"),
  C("na", 516, "Намибия", "Namibia", "en"),
  C("nr", 520, "Науру", "Nauru", "en"),
  C("np", 524, "Непал", "Nepal", "ne"),
  C("nl", 528, "Нидерланды", "Netherlands", "nl", ["nederland", "netherland", "holland"]),
  C("nc", 540, "Новая Каледония", "New Caledonia", "fr"),
  C("nz", 554, "Новая Зеландия", "New Zealand", "en", ["kiwi"]),
  C("ni", 558, "Никарагуа", "Nicaragua", "es"),
  C("ne", 562, "Нигер", "Niger", "fr"),
  C("ng", 566, "Нигерия", "Nigeria", "en", ["naija"]),
  C("nu", 570, "Ниуэ", "Niue", "en"),
  C("nf", 574, "Остров Норфолк", "Norfolk Island", "en"),
  C("mk", 807, "Северная Македония", "North Macedonia", "mk", ["makedonija"]),
  C("mp", 580, "Северные Марианские острова", "Northern Mariana Islands", "en"),
  C("no", 578, "Норвегия", "Norway", "no", ["norge"]),
  C("om", 512, "Оман", "Oman", "ar"),
  C("pk", 586, "Пакистан", "Pakistan", "en"),
  C("pw", 585, "Палау", "Palau", "en"),
  C("ps", 275, "Палестина", "Palestine", "ar"),
  C("pa", 591, "Панама", "Panama", "es"),
  C("pg", 598, "Папуа — Новая Гвинея", "Papua New Guinea", "en"),
  C("py", 600, "Парагвай", "Paraguay", "es"),
  C("pe", 604, "Перу", "Peru", "es"),
  C("ph", 608, "Филиппины", "Philippines", "en", ["pinoy", "pilipinas"]),
  C("pn", 612, "Питкэрн", "Pitcairn", "en"),
  C("pl", 616, "Польша", "Poland", "pl", ["polska"]),
  C("pt", 620, "Португалия", "Portugal", "pt"),
  C("pr", 630, "Пуэрто-Рико", "Puerto Rico", "es"),
  C("qa", 634, "Катар", "Qatar", "ar"),
  C("re", 638, "Реюньон", "Réunion", "fr"),
  C("ro", 642, "Румыния", "Romania", "ro"),
  C("ru", 643, "Россия", "Russia", "ru", ["rossiya"]),
  C("rw", 646, "Руанда", "Rwanda", "en"),
  C("bl", 652, "Сен-Бартелеми", "Saint Barthélemy", "fr"),
  C("sh", 654, "Остров Святой Елены", "Saint Helena", "en"),
  C("kn", 659, "Сент-Китс и Невис", "Saint Kitts and Nevis", "en"),
  C("lc", 662, "Сент-Люсия", "Saint Lucia", "en"),
  C("mf", 663, "Сен-Мартен", "Saint Martin", "fr"),
  C("pm", 666, "Сен-Пьер и Микелон", "Saint Pierre and Miquelon", "fr"),
  C("vc", 670, "Сент-Винсент и Гренадины", "Saint Vincent and the Grenadines", "en"),
  C("ws", 882, "Самоа", "Samoa", "en"),
  C("sm", 674, "Сан-Марино", "San Marino", "it"),
  C("st", 678, "Сан-Томе и Принсипи", "São Tomé and Príncipe", "pt"),
  C("sa", 682, "Саудовская Аравия", "Saudi Arabia", "ar", ["ksa"]),
  C("sn", 686, "Сенегал", "Senegal", "fr"),
  C("rs", 688, "Сербия", "Serbia", "sr", ["srbija"]),
  C("sc", 690, "Сейшелы", "Seychelles", "en"),
  C("sl", 694, "Сьерра-Леоне", "Sierra Leone", "en"),
  C("sg", 702, "Сингапур", "Singapore", "en"),
  C("sx", 534, "Синт-Мартен", "Sint Maarten", "nl"),
  C("sk", 703, "Словакия", "Slovakia", "sk", ["slovensko"]),
  C("si", 705, "Словения", "Slovenia", "sl", ["slovenija"]),
  C("sb", 90, "Соломоновы Острова", "Solomon Islands", "en"),
  C("so", 706, "Сомали", "Somalia", "so"),
  C("za", 710, "ЮАР", "South Africa", "en", ["mzansi"]),
  C("kr", 410, "Южная Корея", "South Korea", "ko", ["hanguk"]),
  C("ss", 728, "Южный Судан", "South Sudan", "en"),
  C("es", 724, "Испания", "Spain", "es", ["espana"]),
  C("lk", 144, "Шри-Ланка", "Sri Lanka", "en"),
  C("sd", 729, "Судан", "Sudan", "ar"),
  C("sr", 740, "Суринам", "Suriname", "nl"),
  C("se", 752, "Швеция", "Sweden", "sv", ["sverige"]),
  C("ch", 756, "Швейцария", "Switzerland", "de", ["schweiz", "suisse", "svizzera"]),
  C("sy", 760, "Сирия", "Syria", "ar"),
  C("tw", 158, "Тайвань", "Taiwan", "zh-TW"),
  C("tj", 762, "Таджикистан", "Tajikistan", "ru"),
  C("tz", 834, "Танзания", "Tanzania", "en"),
  C("th", 764, "Таиланд", "Thailand", "th"),
  C("tl", 626, "Восточный Тимор", "Timor-Leste", "pt"),
  C("tg", 768, "Того", "Togo", "fr"),
  C("tk", 772, "Токелау", "Tokelau", "en"),
  C("to", 776, "Тонга", "Tonga", "en"),
  C("tt", 780, "Тринидад и Тобаго", "Trinidad and Tobago", "en"),
  C("tn", 788, "Тунис", "Tunisia", "fr"),
  C("tr", 792, "Турция", "Turkey", "tr", ["turkiye"]),
  C("tm", 795, "Туркменистан", "Turkmenistan", "ru"),
  C("tc", 796, "Тёркс и Кайкос", "Turks and Caicos Islands", "en"),
  C("tv", 798, "Тувалу", "Tuvalu", "en"),
  C("ug", 800, "Уганда", "Uganda", "en"),
  C("ua", 804, "Украина", "Ukraine", "uk", ["ukraina", "ukr"]),
  C("ae", 784, "ОАЭ", "United Arab Emirates", "en", ["uae", "emirates", "dubai"]),
  C("gb", 826, "Великобритания", "United Kingdom", "en", ["uk", "britain", "england"]),
  C("us", 840, "США", "United States", "en", ["usa", "america"]),
  C("uy", 858, "Уругвай", "Uruguay", "es"),
  C("uz", 860, "Узбекистан", "Uzbekistan", "ru"),
  C("vu", 548, "Вануату", "Vanuatu", "en"),
  C("va", 336, "Ватикан", "Vatican", "it"),
  C("ve", 862, "Венесуэла", "Venezuela", "es"),
  C("vn", 704, "Вьетнам", "Vietnam", "vi", ["vietnam"]),
  C("vg", 92, "Британские Виргинские острова", "British Virgin Islands", "en"),
  C("vi", 850, "Американские Виргинские острова", "US Virgin Islands", "en"),
  C("wf", 876, "Уоллис и Футуна", "Wallis and Futuna", "fr"),
  C("ye", 887, "Йемен", "Yemen", "ar"),
  C("zm", 894, "Замбия", "Zambia", "en"),
  C("zw", 716, "Зимбабве", "Zimbabwe", "en"),
  C("bq", 535, "Карибские Нидерланды", "Caribbean Netherlands", "nl"),
].sort((a, b) => a.name.localeCompare(b.name, "ru"));

const BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));

export function countryByCode(code: string): Country | null {
  return BY_CODE.get(code.trim().toLowerCase()) ?? null;
}

/** location_code DataForSEO для страны. */
export function dfsLocationCode(c: Country): number {
  return 2000 + c.numeric;
}

const fold = (s: string) => s.toLowerCase().replace(/ё/g, "е").replace(/[^a-zа-я0-9\s]/g, " ").replace(/\s+/g, " ").trim();

/** Поиск по подстроке: по-русски, по-английски, по коду и местным названиям. Пустой запрос — популярные страны. */
export function searchCountries(query: string, limit = 12): Country[] {
  const q = fold(query);
  if (!q) return COUNTRIES.filter((c) => POPULAR.includes(c.code)).sort((a, b) => POPULAR.indexOf(a.code) - POPULAR.indexOf(b.code)).slice(0, limit);
  const score = (c: Country): number => {
    const ru = fold(c.name);
    const en = fold(c.en);
    if (c.code === q) return 0;
    if (ru.startsWith(q) || en.startsWith(q)) return 1;
    if (ru.split(" ").some((w) => w.startsWith(q)) || en.split(" ").some((w) => w.startsWith(q))) return 2;
    if (ru.includes(q) || en.includes(q)) return 3;
    if ((c.words ?? []).some((w) => w.startsWith(q))) return 4;
    return 99;
  };
  return COUNTRIES.map((c) => ({ c, s: score(c) }))
    .filter((x) => x.s < 99)
    .sort((a, b) => a.s - b.s || a.c.name.localeCompare(b.c.name, "ru"))
    .slice(0, limit)
    .map((x) => x.c);
}

export const POPULAR = ["nl", "de", "gb", "us", "ca", "au", "be", "at", "ch", "fr", "es", "it", "pl", "pt", "br", "nz", "ie", "za", "in", "ng", "ke", "zm", "jp", "kr"];
