/**
 * Данные шрифтов: библиотека семейств (базовые + пак v9, роли исправлены,
 * начертания сверены с FONT_META) и пары шрифтов (базовые + пак v9).
 * Сгенерировано из legacy canvasFonts.ts + canvas-expansion-v9.json.
 */
export type FontRole = "serif" | "display" | "sans" | "soft" | "script" | "mono";

export interface CanvasFontDef {
  family: string;
  role: FontRole;
  /** Доступные начертания. */
  weights: number[];
  /** Письменности, которые семейство реально поддерживает. */
  scripts: string[];
}

export interface FontPairDef {
  id: string; name: string;
  display: string; sans: string; body: string;
  /** Рукописный акцент (кикер). */
  script?: string;
  themes?: string[];
  mood?: string[];
}

export const FONT_LIBRARY_RAW: CanvasFontDef[] = [
  { family: "Playfair Display", role: "serif", weights: [400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Cormorant", role: "serif", weights: [300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Lora", role: "serif", weights: [400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Bitter", role: "serif", weights: [200, 300, 400, 600, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Prata", role: "serif", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Spectral", role: "serif", weights: [200, 300, 400, 600, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "PT Serif", role: "serif", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Alice", role: "serif", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "EB Garamond", role: "serif", weights: [400, 500, 600, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Literata", role: "serif", weights: [300, 400, 500, 600, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Unbounded", role: "display", weights: [200, 300, 400, 500, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Oswald", role: "display", weights: [200, 300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Alumni Sans", role: "display", weights: [200, 400, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Rubik One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Russo One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Cuprum", role: "display", weights: [400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Playfair Display SC", role: "display", weights: [400, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Montserrat", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Manrope", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Onest", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Inter", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Rubik", role: "sans", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Nunito", role: "sans", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Golos Text", role: "sans", weights: [400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Jost", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Raleway", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Commissioner", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Wix Madefor Display", role: "sans", weights: [400, 500, 600, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Piazzolla", role: "serif", weights: [300, 400, 600, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Comfortaa", role: "soft", weights: [300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Baloo 2", role: "soft", weights: [400, 500, 600, 700, 800], scripts: ["latin"] },
  { family: "Ruda", role: "soft", weights: [400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Podkova", role: "soft", weights: [400, 500, 600, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Yeseva One", role: "soft", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Caveat", role: "script", weights: [400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Marck Script", role: "script", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Bad Script", role: "script", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Pacifico", role: "script", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Anton", role: "display", weights: [400], scripts: ["latin"] },
  { family: "Archivo Black", role: "display", weights: [400], scripts: ["latin"] },
  { family: "Bebas Neue", role: "display", weights: [400], scripts: ["latin"] },
  { family: "Fjalla One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Alfa Slab One", role: "display", weights: [400], scripts: ["latin"] },
  { family: "Archivo Narrow", role: "display", weights: [400, 500, 600, 700], scripts: ["latin"] },
  { family: "Big Shoulders Display", role: "display", weights: [200, 300, 400, 600, 700, 800, 900], scripts: ["latin"] },
  { family: "Bowlby One SC", role: "display", weights: [400], scripts: ["latin"] },
  { family: "Syne", role: "display", weights: [400, 500, 600, 700, 800], scripts: ["latin"] },
  { family: "Bricolage Grotesque", role: "display", weights: [300, 400, 500, 600, 700, 800], scripts: ["latin"] },
  { family: "Kanit", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800, 900], scripts: ["latin"] },
  { family: "Chivo", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800, 900], scripts: ["latin"] },
  { family: "Fira Sans Extra Condensed", role: "sans", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Space Grotesk", role: "sans", weights: [300, 400, 500, 600, 700], scripts: ["latin"] },
  { family: "Archivo", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800, 900], scripts: ["latin"] },
  { family: "Barlow Condensed", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800, 900], scripts: ["latin"] },
  { family: "Tenor Sans", role: "sans", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Cormorant Garamond", role: "serif", weights: [300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Merriweather", role: "serif", weights: [300, 400, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Source Serif 4", role: "serif", weights: [300, 400, 500, 600, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Instrument Serif", role: "serif", weights: [400], scripts: ["latin"] },
  { family: "Caveat Brush", role: "script", weights: [400], scripts: ["latin"] },
  { family: "Amatic SC", role: "script", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Gloria Hallelujah", role: "script", weights: [400], scripts: ["latin"] },
  { family: "Shantell Sans", role: "script", weights: [300, 400, 500, 600, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Roboto", role: "sans", weights: [100, 300, 400, 500, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Roboto Condensed", role: "sans", weights: [300, 400, 500, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Open Sans", role: "sans", weights: [300, 400, 500, 600, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Source Sans 3", role: "sans", weights: [200, 300, 400, 600, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Nunito Sans", role: "sans", weights: [200, 300, 400, 600, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Fira Sans", role: "sans", weights: [100, 300, 400, 500, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Fira Sans Condensed", role: "sans", weights: [300, 400, 500, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "IBM Plex Sans", role: "sans", weights: [200, 300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "PT Sans Narrow", role: "sans", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Exo 2", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Ubuntu", role: "sans", weights: [300, 400, 500, 700], scripts: ["latin", "cyrillic"] },
  { family: "Play", role: "sans", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Geologica", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Alegreya Sans", role: "sans", weights: [300, 400, 500, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Merriweather Sans", role: "sans", weights: [300, 400, 500, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Roboto Slab", role: "serif", weights: [200, 300, 400, 500, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "IBM Plex Serif", role: "serif", weights: [200, 300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Noto Serif", role: "serif", weights: [300, 400, 500, 600, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Alegreya", role: "serif", weights: [400, 500, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Vollkorn", role: "serif", weights: [400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Tektur", role: "display", weights: [400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Yanone Kaffeesatz", role: "display", weights: [200, 300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Rubik Mono One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Stalinist One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Kelly Slab", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "JetBrains Mono", role: "mono", weights: [200, 300, 400, 500, 600, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Roboto Mono", role: "mono", weights: [200, 300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "IBM Plex Mono", role: "mono", weights: [200, 300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Inter Tight", role: "sans", weights: [200, 300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Wix Madefor Text", role: "sans", weights: [400, 500, 600, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Scada", role: "sans", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Kurale", role: "serif", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Ledger", role: "serif", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Marmelad", role: "soft", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Cormorant Infant", role: "serif", weights: [300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Andika", role: "sans", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Forum", role: "serif", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Philosopher", role: "serif", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Oranienbaum", role: "serif", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Old Standard TT", role: "serif", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Bona Nova", role: "serif", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Cormorant SC", role: "serif", weights: [300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Cormorant Unicase", role: "serif", weights: [300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Noto Serif Display", role: "serif", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Playfair", role: "serif", weights: [400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Gabriela", role: "serif", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Orelega One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Viaoda Libre", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Kaisei Tokumin", role: "serif", weights: [400, 500, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Kaisei Decol", role: "serif", weights: [400, 500, 700], scripts: ["latin", "cyrillic"] },
  { family: "Zen Antique", role: "serif", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Brygada 1918", role: "serif", weights: [400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Roboto Serif", role: "serif", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "STIX Two Text", role: "serif", weights: [400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Alegreya SC", role: "serif", weights: [400, 500, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Spectral SC", role: "serif", weights: [300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Arsenal", role: "sans", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Mulish", role: "sans", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Sofia Sans", role: "sans", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Sofia Sans Condensed", role: "sans", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Sofia Sans Extra Condensed", role: "display", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Ysabeau", role: "sans", weights: [300, 400, 500, 600, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Montserrat Alternates", role: "sans", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Overpass", role: "sans", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Didact Gothic", role: "sans", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "IBM Plex Sans Condensed", role: "sans", weights: [300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Noto Sans Display", role: "sans", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Advent Pro", role: "sans", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Jura", role: "sans", weights: [300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "M PLUS Rounded 1c", role: "soft", weights: [300, 400, 500, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Zen Maru Gothic", role: "soft", weights: [300, 400, 500, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Balsamiq Sans", role: "soft", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Bellota", role: "soft", weights: [300, 400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Poiret One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "El Messiri", role: "display", weights: [400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Days One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Dela Gothic One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Oi", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Seymour One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Rampart One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Reggae One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Alumni Sans Collegiate One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Rubik Dirt", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Rubik Distressed", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Rubik Wet Paint", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Rubik Spray Paint", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Rubik Marker Hatch", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Lobster", role: "script", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Pattaya", role: "script", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Great Vibes", role: "script", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Comforter Brush", role: "script", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Neucha", role: "script", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Pangolin", role: "script", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "PT Mono", role: "mono", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Martian Mono", role: "mono", weights: [300, 400, 500, 600, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "Ruslan Display", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Underdog", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Pixelify Sans", role: "display", weights: [400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Handjet", role: "display", weights: [300, 400, 600, 800], scripts: ["latin", "cyrillic"] },
  { family: "Yuji Syuku", role: "serif", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Train One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Tinos", role: "serif", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Vollkorn SC", role: "serif", weights: [400, 600, 700, 900], scripts: ["latin", "cyrillic"] },
  { family: "Alegreya Sans SC", role: "sans", weights: [300, 400, 500, 700, 800], scripts: ["latin", "cyrillic"] },
  { family: "PT Serif Caption", role: "serif", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "PT Sans Caption", role: "sans", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Bona Nova SC", role: "serif", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Sofia Sans Semi Condensed", role: "sans", weights: [300, 400, 500, 600, 700, 800, 900], scripts: ["latin", "cyrillic"] },
  { family: "Gentium Book Plus", role: "serif", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Rubik Scribble", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Rubik Doodle Shadow", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Rubik Bubbles", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Rubik Vinyl", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Rubik Glitch", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Rubik Burned", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Kablammo", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Prosto One", role: "display", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Ubuntu Condensed", role: "sans", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Ubuntu Mono", role: "mono", weights: [400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Fira Code", role: "mono", weights: [300, 400, 500, 600, 700], scripts: ["latin", "cyrillic"] },
  { family: "Comforter", role: "script", weights: [400], scripts: ["latin", "cyrillic"] },
  { family: "Bellota Text", role: "soft", weights: [300, 400, 700], scripts: ["latin", "cyrillic"] },
  { family: "Charis SIL", role: "serif", weights: [400, 700], scripts: ["latin", "cyrillic"] },
];

export const FONT_PAIRS_RAW: FontPairDef[] = [
  { id: "editorial", name: "Editorial", display: "Playfair Display", sans: "Montserrat", body: "Manrope" },
  { id: "magazine", name: "Magazine", display: "Cormorant", sans: "Oswald", body: "Lora" },
  { id: "luxe", name: "Luxe", display: "Prata", sans: "Jost", body: "Spectral" },
  { id: "bold", name: "Bold", display: "Unbounded", sans: "Unbounded", body: "Manrope" },
  { id: "poster", name: "Poster", display: "Russo One", sans: "Oswald", body: "Rubik" },
  { id: "modern", name: "Modern", display: "Onest", sans: "Inter", body: "Inter" },
  { id: "clean", name: "Clean", display: "Golos Text", sans: "Commissioner", body: "Manrope" },
  { id: "soft", name: "Soft", display: "Baloo 2", sans: "Nunito", body: "Comfortaa" },
  { id: "classic", name: "Classic", display: "EB Garamond", sans: "Raleway", body: "Literata" },
  { id: "handwritten", name: "Handwritten", display: "Yeseva One", sans: "Rubik", body: "Caveat" },
  { id: "sport", name: "Sport", display: "Alumni Sans", sans: "Cuprum", body: "Ruda" },
  { id: "serifsans", name: "Serif + Sans", display: "Bitter", sans: "Wix Madefor Display", body: "Manrope" },
  { id: "brush-pop", name: "Brush Pop", display: "Caveat Brush", sans: "Archivo Black", body: "Archivo", script: "Caveat Brush" },
  { id: "anton-grid", name: "Anton Grid", display: "Anton", sans: "Archivo", body: "Archivo", script: "Caveat" },
  { id: "swiss-giant", name: "Swiss Giant", display: "Archivo Black", sans: "Archivo", body: "Archivo", script: "Caveat" },
  { id: "tabloid", name: "Tabloid", display: "Alfa Slab One", sans: "Fira Sans Extra Condensed", body: "Chivo", script: "Caveat Brush" },
  { id: "zine-condensed", name: "Zine Condensed", display: "Bebas Neue", sans: "Barlow Condensed", body: "Chivo", script: "Amatic SC" },
  { id: "quiet-luxury", name: "Quiet Luxury", display: "Tenor Sans", sans: "Jost", body: "Cormorant Garamond", script: "Caveat" },
  { id: "editorial-serif", name: "Editorial Serif", display: "Instrument Serif", sans: "Space Grotesk", body: "Source Serif 4", script: "Caveat" },
  { id: "gallery-mag", name: "Gallery Magazine", display: "Cormorant Garamond", sans: "Archivo Narrow", body: "Source Serif 4", script: "Caveat" },
  { id: "neo-grotesk", name: "Neo Grotesk", display: "Bricolage Grotesque", sans: "Space Grotesk", body: "Archivo", script: "Shantell Sans" },
  { id: "syne-art", name: "Syne Art", display: "Syne", sans: "Space Grotesk", body: "Archivo", script: "Shantell Sans" },
  { id: "stadium", name: "Stadium", display: "Big Shoulders Display", sans: "Fira Sans Extra Condensed", body: "Chivo", script: "Caveat Brush" },
  { id: "sticker-club", name: "Sticker Club", display: "Bowlby One SC", sans: "Kanit", body: "Archivo", script: "Gloria Hallelujah" },
  { id: "slab-news", name: "Slab News", display: "Merriweather", sans: "Fjalla One", body: "Chivo", script: "Caveat" },
  { id: "kanit-pop", name: "Kanit Pop", display: "Kanit", sans: "Kanit", body: "Archivo", script: "Shantell Sans" },
  { id: "fjalla-clean", name: "Fjalla Clean", display: "Fjalla One", sans: "Archivo", body: "Archivo", script: "Caveat" },
  { id: "airy-thin", name: "Airy Thin", display: "Jost", sans: "Manrope", body: "Manrope", script: "Caveat" },
  { id: "light-serif", name: "Light Serif", display: "Cormorant Garamond", sans: "Raleway", body: "Spectral", script: "Caveat" },
  { id: "mid-neutral", name: "Mid Neutral", display: "Geologica", sans: "Geologica", body: "Inter", script: "Caveat" },
  { id: "tech-mono", name: "Tech", display: "Tektur", sans: "Space Grotesk", body: "IBM Plex Sans", script: "Shantell Sans" },
  { id: "news-slab", name: "News Slab", display: "Roboto Slab", sans: "Roboto Condensed", body: "Noto Serif", script: "Caveat" },
  { id: "plex-editorial", name: "Plex Editorial", display: "IBM Plex Serif", sans: "IBM Plex Sans", body: "IBM Plex Sans", script: "Caveat" },
  { id: "narrow-press", name: "Narrow Press", display: "PT Sans Narrow", sans: "Fira Sans Condensed", body: "Fira Sans", script: "Caveat Brush" },
  { id: "kaffee", name: "Kaffeesatz", display: "Yanone Kaffeesatz", sans: "Nunito Sans", body: "Nunito Sans", script: "Caveat" },
  { id: "retro-block", name: "Retro Block", display: "Rubik Mono One", sans: "Rubik", body: "Rubik", script: "Gloria Hallelujah" },
  { id: "brutal", name: "Brutal", display: "Stalinist One", sans: "Roboto Condensed", body: "Roboto", script: "Caveat Brush" },
  { id: "slab-kelly", name: "Kelly Slab", display: "Kelly Slab", sans: "Open Sans", body: "Open Sans", script: "Caveat" },
  { id: "alegreya-mag", name: "Alegreya Magazine", display: "Alegreya", sans: "Alegreya Sans", body: "Alegreya", script: "Caveat" },
  { id: "vollkorn-book", name: "Vollkorn Book", display: "Vollkorn", sans: "Source Sans 3", body: "Vollkorn", script: "Caveat" },
  { id: "exo-sport", name: "Exo Sport", display: "Exo 2", sans: "Exo 2", body: "Ubuntu", script: "Caveat Brush" },
  { id: "ubuntu-soft", name: "Ubuntu Soft", display: "Ubuntu", sans: "Ubuntu", body: "Open Sans", script: "Caveat" },
  { id: "play-poster", name: "Play Poster", display: "Play", sans: "Roboto", body: "Roboto", script: "Caveat" },
  { id: "merri-clean", name: "Merri Clean", display: "Merriweather", sans: "Merriweather Sans", body: "Merriweather Sans", script: "Caveat" },
  { id: "fira-editorial", name: "Fira Editorial", display: "Fira Sans", sans: "Fira Sans Condensed", body: "Fira Sans", script: "Caveat" },
  { id: "roboto-mix", name: "Roboto Mix", display: "Roboto", sans: "Roboto Condensed", body: "Roboto Slab", script: "Caveat" },
  { id: "source-quiet", name: "Source Quiet", display: "Source Serif 4", sans: "Source Sans 3", body: "Source Sans 3", script: "Caveat" },
  { id: "anton-mono", name: "Anton × Mono", display: "Anton", sans: "JetBrains Mono", body: "Inter Tight", script: "Caveat" },
  { id: "bebas-plex", name: "Bebas × Plex", display: "Bebas Neue", sans: "IBM Plex Sans", body: "IBM Plex Sans", script: "Caveat" },
  { id: "prata-tight", name: "Prata × Tight", display: "Prata", sans: "Inter Tight", body: "Manrope", script: "Caveat" },
  { id: "instrument-mono", name: "Instrument × Mono", display: "Instrument Serif", sans: "Roboto Mono", body: "Manrope", script: "Caveat" },
  { id: "syne-tight", name: "Syne × Tight", display: "Syne", sans: "Inter Tight", body: "Inter Tight", script: "Shantell Sans" },
  { id: "unbounded-madefor", name: "Unbounded × Madefor", display: "Unbounded", sans: "Wix Madefor Text", body: "Wix Madefor Text", script: "Caveat" },
  { id: "cormorant-jost", name: "Cormorant Infant × Jost", display: "Cormorant Infant", sans: "Jost", body: "Cormorant Infant", script: "Caveat" },
  { id: "kurale-grotesk", name: "Kurale × Grotesk", display: "Kurale", sans: "Space Grotesk", body: "Manrope", script: "Caveat" },
  { id: "ledger-tight", name: "Ledger × Tight", display: "Ledger", sans: "Inter Tight", body: "Inter Tight", script: "Caveat" },
  { id: "archivo-jet", name: "Archivo Black × Jet", display: "Archivo Black", sans: "JetBrains Mono", body: "Archivo", script: "Caveat" },
  { id: "oswald-madefor", name: "Oswald × Madefor", display: "Oswald", sans: "Wix Madefor Text", body: "Manrope", script: "Caveat" },
  { id: "bricolage-plexmono", name: "Bricolage × Plex Mono", display: "Bricolage Grotesque", sans: "IBM Plex Mono", body: "Archivo", script: "Shantell Sans" },
  { id: "marmelad-onest", name: "Marmelad × Onest", display: "Marmelad", sans: "Onest", body: "Onest", script: "Caveat" },
  { id: "yeseva-scada", name: "Yeseva × Scada", display: "Yeseva One", sans: "Scada", body: "Scada", script: "Caveat" },
  { id: "playfair-jet", name: "Playfair × Jet", display: "Playfair Display", sans: "JetBrains Mono", body: "Spectral", script: "Caveat" },
  { id: "tenor-mono", name: "Tenor × Mono", display: "Tenor Sans", sans: "Roboto Mono", body: "Jost", script: "Caveat" },
  { id: "bigshoulders-inter", name: "Big Shoulders × Inter", display: "Big Shoulders Display", sans: "Inter Tight", body: "Inter", script: "Caveat Brush" },
  { id: "alfa-madefor", name: "Alfa Slab × Madefor", display: "Alfa Slab One", sans: "Wix Madefor Text", body: "Chivo", script: "Caveat Brush" },
  { id: "spectral-tight", name: "Spectral × Tight", display: "Spectral", sans: "Inter Tight", body: "Spectral", script: "Caveat" },
  { id: "geologica-plexmono", name: "Geologica × Plex Mono", display: "Geologica", sans: "IBM Plex Mono", body: "Inter", script: "Caveat" },
  { id: "russo-scada", name: "Russo × Scada", display: "Russo One", sans: "Scada", body: "Scada", script: "Caveat" },
  { id: "fjalla-jet", name: "Fjalla × Jet", display: "Fjalla One", sans: "JetBrains Mono", body: "Archivo", script: "Caveat" },
  { id: "eb-mono", name: "Garamond × Mono", display: "EB Garamond", sans: "Roboto Mono", body: "EB Garamond", script: "Caveat" },
  { id: "kanit-madefor", name: "Kanit × Madefor", display: "Kanit", sans: "Wix Madefor Text", body: "Manrope", script: "Shantell Sans" },
  { id: "vollkorn-tight", name: "Vollkorn × Tight", display: "Vollkorn", sans: "Inter Tight", body: "Vollkorn", script: "Caveat" },
  { id: "bowlby-onest", name: "Bowlby × Onest", display: "Bowlby One SC", sans: "Onest", body: "Onest", script: "Gloria Hallelujah" },
  { id: "cuprum-serif", name: "Cuprum × Serif", display: "Cuprum", sans: "Cuprum", body: "Kurale", script: "Caveat" },
  { id: "andika-anton", name: "Anton × Andika", display: "Anton", sans: "Andika", body: "Andika", script: "Caveat" },
  { id: "lora-grotesk", name: "Lora × Grotesk", display: "Lora", sans: "Space Grotesk", body: "Lora", script: "Caveat" },
  { id: "tektur-plex", name: "Tektur × Plex", display: "Tektur", sans: "IBM Plex Sans", body: "IBM Plex Mono", script: "Shantell Sans" },
  { id: "bitter-jet", name: "Bitter × Jet", display: "Bitter", sans: "JetBrains Mono", body: "Bitter", script: "Caveat" },
  { id: "commissioner-serif", name: "Commissioner × Serif", display: "Commissioner", sans: "Commissioner", body: "Ledger", script: "Caveat" },
  { id: "rubikmono-madefor", name: "Rubik Mono × Madefor", display: "Rubik Mono One", sans: "Wix Madefor Text", body: "Rubik", script: "Caveat Brush" },
  { id: "literata-tight", name: "Literata × Tight", display: "Literata", sans: "Inter Tight", body: "Literata", script: "Caveat" },
  { id: "alumni-plexmono", name: "Alumni × Plex Mono", display: "Alumni Sans", sans: "IBM Plex Mono", body: "Chivo", script: "Caveat Brush" },
  { id: "notoserif-onest", name: "Noto Serif × Onest", display: "Noto Serif", sans: "Onest", body: "Noto Serif", script: "Caveat" },
  { id: "jost-kurale", name: "Jost × Kurale", display: "Jost", sans: "Jost", body: "Kurale", script: "Caveat" },
  { id: "chivo-instrument", name: "Chivo × Instrument", display: "Instrument Serif", sans: "Chivo", body: "Chivo", script: "Caveat" },
  { id: "raleway-ledger", name: "Raleway × Ledger", display: "Raleway", sans: "Raleway", body: "Ledger", script: "Caveat" },
  { id: "manrope-prata", name: "Prata × Manrope", display: "Prata", sans: "Manrope", body: "Manrope", script: "Caveat" },
  { id: "vogue-cyr", name: "Vogue Cyr", display: "Playfair Display", sans: "Jost", body: "Cormorant Garamond", script: "Great Vibes", themes: ["beauty-fashion"], mood: ["editorial"] },
  { id: "forum-muse", name: "Forum Muse", display: "Forum", sans: "Mulish", body: "Mulish", script: "Marck Script", themes: ["beauty-fashion", "home-decor"], mood: ["editorial"] },
  { id: "poiret-deco", name: "Poiret Deco", display: "Poiret One", sans: "Jost", body: "Jost", script: "Bad Script", themes: ["beauty-fashion", "tattoo"], mood: ["airy"] },
  { id: "bona-editorial", name: "Bona Editorial", display: "Bona Nova", sans: "Sofia Sans", body: "Bona Nova", script: "Caveat", themes: ["beauty-fashion", "home-decor"], mood: ["editorial"] },
  { id: "cormorant-sc-lux", name: "Cormorant SC Lux", display: "Cormorant SC", sans: "Montserrat", body: "Cormorant Garamond", script: "Great Vibes", themes: ["beauty-fashion", "tattoo"], mood: ["luxe"] },
  { id: "unicase-atelier", name: "Unicase Atelier", display: "Cormorant Unicase", sans: "Raleway", body: "Spectral", script: "Marck Script", themes: ["beauty-fashion", "tattoo"], mood: ["luxe"] },
  { id: "noto-display-glow", name: "Noto Display Glow", display: "Noto Serif Display", sans: "Manrope", body: "Noto Serif", script: "Comforter Brush", themes: ["beauty-fashion", "blog-info"], mood: ["editorial"] },
  { id: "ysabeau-skin", name: "Ysabeau Skin", display: "Ysabeau", sans: "Mulish", body: "Ysabeau", script: "Bad Script", themes: ["beauty-fashion"], mood: ["airy"] },
  { id: "oranienbaum-salon", name: "Oranienbaum Salon", display: "Oranienbaum", sans: "Commissioner", body: "Literata", script: "Marck Script", themes: ["beauty-fashion", "tattoo"], mood: ["editorial"] },
  { id: "viaoda-couture", name: "Viaoda Couture", display: "Viaoda Libre", sans: "Inter Tight", body: "Spectral", script: "Great Vibes", themes: ["beauty-fashion", "tattoo"], mood: ["luxe"] },
  { id: "unbounded-gloss", name: "Unbounded Gloss", display: "Unbounded", sans: "Onest", body: "Onest", script: "Pacifico", themes: ["beauty-fashion"], mood: ["pop"] },
  { id: "dela-pop", name: "Dela Pop", display: "Dela Gothic One", sans: "Golos Text", body: "Golos Text", script: "Caveat Brush", themes: ["beauty-fashion", "food"], mood: ["pop"] },
  { id: "montserrat-alt-chic", name: "Montserrat Alt Chic", display: "Montserrat Alternates", sans: "Montserrat", body: "Manrope", script: "Pacifico", themes: ["beauty-fashion"], mood: ["pop"] },
  { id: "playfair-sc-cover", name: "Playfair SC Cover", display: "Playfair Display SC", sans: "Sofia Sans Condensed", body: "Lora", script: "Great Vibes", themes: ["beauty-fashion", "tattoo"], mood: ["luxe"] },
  { id: "tenor-whisper", name: "Tenor Whisper", display: "Tenor Sans", sans: "Didact Gothic", body: "Cormorant Infant", script: "Bad Script", themes: ["beauty-fashion", "home-decor"], mood: ["airy"] },
  { id: "playfair-var-muse", name: "Playfair Muse", display: "Playfair", sans: "Mulish", body: "Lora", script: "Marck Script", themes: ["beauty-fashion", "home-decor"], mood: ["editorial"] },
  { id: "kaisei-japandi", name: "Kaisei Japandi", display: "Kaisei Tokumin", sans: "Zen Maru Gothic", body: "Zen Maru Gothic", script: "Caveat", themes: ["home-decor"], mood: ["calm"] },
  { id: "brygada-farmhouse", name: "Brygada Farmhouse", display: "Brygada 1918", sans: "Mulish", body: "Brygada 1918", script: "Marck Script", themes: ["home-decor", "food"], mood: ["heritage"] },
  { id: "old-standard-heritage", name: "Old Standard Heritage", display: "Old Standard TT", sans: "Raleway", body: "Old Standard TT", script: "Bad Script", themes: ["home-decor", "tattoo"], mood: ["heritage"] },
  { id: "roboto-serif-scandi", name: "Roboto Serif Scandi", display: "Roboto Serif", sans: "Inter", body: "Inter", script: "Caveat", themes: ["home-decor", "blog-info"], mood: ["calm"] },
  { id: "philosopher-loft", name: "Philosopher Loft", display: "Philosopher", sans: "Overpass", body: "Overpass", script: "Neucha", themes: ["home-decor"], mood: ["calm"] },
  { id: "arsenal-nordic", name: "Arsenal Nordic", display: "Arsenal", sans: "Arsenal", body: "Literata", script: "Caveat", themes: ["home-decor", "blog-info"], mood: ["calm"] },
  { id: "orelega-maximal", name: "Orelega Maximal", display: "Orelega One", sans: "Commissioner", body: "Commissioner", script: "Pattaya", themes: ["home-decor", "food"], mood: ["pop"] },
  { id: "stix-gallery", name: "STIX Gallery", display: "STIX Two Text", sans: "Sofia Sans", body: "STIX Two Text", script: "Marck Script", themes: ["home-decor", "blog-info"], mood: ["editorial"] },
  { id: "el-messiri-boho", name: "El Messiri Boho", display: "El Messiri", sans: "Nunito Sans", body: "Nunito Sans", script: "Bad Script", themes: ["home-decor"], mood: ["boho"] },
  { id: "spectral-sc-manor", name: "Spectral SC Manor", display: "Spectral SC", sans: "Jost", body: "Spectral", script: "Great Vibes", themes: ["home-decor"], mood: ["luxe"] },
  { id: "gabriela-cottage", name: "Gabriela Cottage", display: "Gabriela", sans: "Mulish", body: "Lora", script: "Marck Script", themes: ["home-decor", "food"], mood: ["heritage"] },
  { id: "advent-minimal", name: "Advent Minimal", display: "Advent Pro", sans: "Manrope", body: "Manrope", script: "Caveat", themes: ["home-decor", "beauty-fashion"], mood: ["airy"] },
  { id: "lora-linen", name: "Lora Linen", display: "Lora", sans: "Sofia Sans", body: "Lora", script: "Bad Script", themes: ["home-decor"], mood: ["calm"] },
  { id: "zen-antique-wabi", name: "Zen Antique Wabi", display: "Zen Antique", sans: "Zen Maru Gothic", body: "Zen Maru Gothic", script: "Caveat", themes: ["home-decor"], mood: ["calm"] },
  { id: "lobster-diner", name: "Lobster Diner", display: "Lobster", sans: "Oswald", body: "Rubik", script: "Lobster", themes: ["food"], mood: ["retro"] },
  { id: "pattaya-bistro", name: "Pattaya Bistro", display: "Pattaya", sans: "Nunito", body: "Nunito", script: "Pattaya", themes: ["food"], mood: ["retro"] },
  { id: "mplus-fresh", name: "M PLUS Fresh", display: "M PLUS Rounded 1c", sans: "M PLUS Rounded 1c", body: "Nunito Sans", script: "Caveat Brush", themes: ["food"], mood: ["friendly"] },
  { id: "balsamiq-homemade", name: "Balsamiq Homemade", display: "Balsamiq Sans", sans: "Balsamiq Sans", body: "Nunito", script: "Neucha", themes: ["food", "blog-info"], mood: ["friendly"] },
  { id: "seymour-burger", name: "Seymour Burger", display: "Seymour One", sans: "Rubik", body: "Rubik", script: "Caveat Brush", themes: ["food"], mood: ["pop"] },
  { id: "sofia-xcond-menu", name: "Sofia XCond Menu", display: "Sofia Sans Extra Condensed", sans: "Sofia Sans Condensed", body: "Sofia Sans", script: "Caveat Brush", themes: ["food", "tattoo", "blog-info"], mood: ["poster"] },
  { id: "yeseva-bakery", name: "Yeseva Bakery", display: "Yeseva One", sans: "Nunito Sans", body: "Lora", script: "Marck Script", themes: ["food", "beauty-fashion"], mood: ["heritage"] },
  { id: "bitter-rustic", name: "Bitter Rustic", display: "Bitter", sans: "Mulish", body: "Bitter", script: "Neucha", themes: ["food"], mood: ["heritage"] },
  { id: "podkova-market", name: "Podkova Market", display: "Podkova", sans: "Rubik", body: "Rubik", script: "Amatic SC", themes: ["food"], mood: ["heritage"] },
  { id: "amatic-farm", name: "Amatic Farm", display: "Amatic SC", sans: "Cuprum", body: "PT Serif", script: "Amatic SC", themes: ["food"], mood: ["handmade"] },
  { id: "alegreya-gourmet", name: "Alegreya Gourmet", display: "Alegreya SC", sans: "Alegreya Sans", body: "Alegreya", script: "Great Vibes", themes: ["food"], mood: ["luxe"] },
  { id: "comfortaa-smoothie", name: "Comfortaa Smoothie", display: "Comfortaa", sans: "Nunito", body: "Nunito", script: "Pacifico", themes: ["food"], mood: ["friendly"] },
  { id: "oi-street-food", name: "Oi Street Food", display: "Oi", sans: "Onest", body: "Onest", script: "Caveat Brush", themes: ["food"], mood: ["pop"] },
  { id: "kurale-grandma", name: "Kurale Grandma", display: "Kurale", sans: "PT Sans Narrow", body: "PT Serif", script: "Bad Script", themes: ["food"], mood: ["heritage"] },
  { id: "reggae-spice", name: "Reggae Spice", display: "Reggae One", sans: "Ubuntu", body: "Ubuntu", script: "Caveat Brush", themes: ["food"], mood: ["pop"] },
  { id: "dirt-ink", name: "Dirt Ink", display: "Rubik Dirt", sans: "Roboto Condensed", body: "Roboto", script: "Caveat Brush", themes: ["tattoo"], mood: ["grunge"] },
  { id: "distressed-parlor", name: "Distressed Parlor", display: "Rubik Distressed", sans: "Oswald", body: "PT Mono", script: "Caveat Brush", themes: ["tattoo"], mood: ["grunge"] },
  { id: "old-standard-flash", name: "Old Standard Flash", display: "Old Standard TT", sans: "PT Sans Narrow", body: "PT Mono", script: "Marck Script", themes: ["tattoo"], mood: ["heritage"] },
  { id: "unicase-ornament", name: "Unicase Ornament", display: "Cormorant Unicase", sans: "Sofia Sans Condensed", body: "Cormorant Garamond", script: "Great Vibes", themes: ["tattoo"], mood: ["luxe"] },
  { id: "playfair-sc-needle", name: "Playfair SC Needle", display: "Playfair Display SC", sans: "Roboto Condensed", body: "Spectral", script: "Bad Script", themes: ["tattoo"], mood: ["luxe"] },
  { id: "sofia-xcond-blackwork", name: "Sofia XCond Blackwork", display: "Sofia Sans Extra Condensed", sans: "Sofia Sans Condensed", body: "IBM Plex Mono", script: "Caveat Brush", themes: ["tattoo"], mood: ["poster"] },
  { id: "collegiate-oldschool", name: "Collegiate Old School", display: "Alumni Sans Collegiate One", sans: "Alumni Sans", body: "PT Serif", script: "Lobster", themes: ["tattoo"], mood: ["retro"] },
  { id: "poiret-fineline", name: "Poiret Fine Line", display: "Poiret One", sans: "Jost", body: "Jost", script: "Bad Script", themes: ["tattoo"], mood: ["airy"] },
  { id: "wetpaint-street", name: "Wet Paint Street", display: "Rubik Wet Paint", sans: "Roboto Condensed", body: "Roboto Mono", script: "Caveat Brush", themes: ["tattoo"], mood: ["grunge"] },
  { id: "spray-graffiti", name: "Spray Graffiti", display: "Rubik Spray Paint", sans: "Oswald", body: "Inter", script: "Caveat Brush", themes: ["tattoo"], mood: ["grunge"] },
  { id: "rampart-neo", name: "Rampart Neo", display: "Rampart One", sans: "Onest", body: "Onest", script: "Caveat Brush", themes: ["tattoo"], mood: ["pop"] },
  { id: "oranienbaum-gothic", name: "Oranienbaum Gothic", display: "Oranienbaum", sans: "Fira Sans Extra Condensed", body: "PT Mono", script: "Marck Script", themes: ["tattoo"], mood: ["heritage"] },
  { id: "viaoda-dark-romance", name: "Viaoda Dark Romance", display: "Viaoda Libre", sans: "Sofia Sans Condensed", body: "Spectral", script: "Great Vibes", themes: ["tattoo"], mood: ["luxe"] },
  { id: "marker-hatch-sketch", name: "Marker Hatch Sketch", display: "Rubik Marker Hatch", sans: "Inter Tight", body: "JetBrains Mono", script: "Caveat", themes: ["tattoo"], mood: ["grunge"] },
  { id: "ysabeau-fineline", name: "Ysabeau Fine Line", display: "Ysabeau", sans: "Didact Gothic", body: "Ysabeau", script: "Bad Script", themes: ["tattoo", "beauty-fashion"], mood: ["airy"] },
  { id: "golos-clarity", name: "Golos Clarity", display: "Golos Text", sans: "Golos Text", body: "Inter", script: "Caveat", themes: ["blog-info"], mood: ["neutral"] },
  { id: "sofia-news", name: "Sofia News", display: "Sofia Sans Condensed", sans: "Sofia Sans", body: "Source Serif 4", script: "Caveat", themes: ["blog-info"], mood: ["poster"] },
  { id: "roboto-serif-longread", name: "Roboto Serif Longread", display: "Roboto Serif", sans: "Inter", body: "Roboto Serif", script: "Caveat", themes: ["blog-info"], mood: ["editorial"] },
  { id: "overpass-signal", name: "Overpass Signal", display: "Overpass", sans: "Overpass", body: "Literata", script: "Shantell Sans", themes: ["blog-info"], mood: ["neutral"] },
  { id: "mulish-friendly", name: "Mulish Friendly", display: "Mulish", sans: "Mulish", body: "Lora", script: "Pangolin", themes: ["blog-info", "food"], mood: ["friendly"] },
  { id: "plex-cond-report", name: "Plex Cond Report", display: "IBM Plex Sans Condensed", sans: "IBM Plex Sans", body: "IBM Plex Serif", script: "Caveat", themes: ["blog-info"], mood: ["neutral"] },
  { id: "days-headline", name: "Days Headline", display: "Days One", sans: "Manrope", body: "Manrope", script: "Caveat Brush", themes: ["blog-info"], mood: ["poster"] },
  { id: "unbounded-explainer", name: "Unbounded Explainer", display: "Unbounded", sans: "Inter Tight", body: "Inter Tight", script: "Shantell Sans", themes: ["blog-info"], mood: ["poster"] },
  { id: "stix-academic", name: "STIX Academic", display: "STIX Two Text", sans: "Source Sans 3", body: "STIX Two Text", script: "Caveat", themes: ["blog-info"], mood: ["editorial"] },
  { id: "neucha-notebook", name: "Neucha Notebook", display: "Neucha", sans: "Nunito", body: "Nunito", script: "Neucha", themes: ["blog-info", "food"], mood: ["handmade"] },
  { id: "pangolin-sketchnote", name: "Pangolin Sketchnote", display: "Pangolin", sans: "Onest", body: "Onest", script: "Pangolin", themes: ["blog-info"], mood: ["handmade"] },
  { id: "jura-tech", name: "Jura Tech", display: "Jura", sans: "Jura", body: "Inter", script: "Shantell Sans", themes: ["blog-info"], mood: ["neutral"] },
  { id: "literata-essay", name: "Literata Essay", display: "Literata", sans: "Commissioner", body: "Literata", script: "Bad Script", themes: ["blog-info", "home-decor"], mood: ["editorial"] },
  { id: "montserrat-impact", name: "Montserrat Impact", display: "Montserrat", sans: "Montserrat", body: "Manrope", script: "Caveat Brush", themes: ["blog-info"], mood: ["poster"] },
  { id: "noto-display-feature", name: "Noto Display Feature", display: "Noto Serif Display", sans: "Noto Sans Display", body: "Noto Serif", script: "Caveat", themes: ["blog-info"], mood: ["editorial"] },
  { id: "salon-sc", name: "Salon SC", display: "Cormorant SC", sans: "Jost", body: "Cormorant Garamond", script: "Great Vibes", themes: ["beauty-fashion"], mood: ["editorial"] },
  { id: "bona-sc-menu", name: "Bona SC Menu", display: "Bona Nova SC", sans: "Didact Gothic", body: "Bona Nova", script: "Comforter", themes: ["beauty-fashion", "food"], mood: ["editorial"] },
  { id: "tenor-price-list", name: "Tenor Price List", display: "Tenor Sans", sans: "Alegreya Sans SC", body: "Alegreya Sans", script: "Marck Script", themes: ["beauty-fashion"], mood: ["airy"] },
  { id: "mplus-aura", name: "Rounded Aura", display: "M PLUS Rounded 1c", sans: "Nunito", body: "Nunito", script: "Pacifico", themes: ["beauty-fashion", "blog-info"], mood: ["soft"] },
  { id: "zenmaru-glow", name: "Zen Maru Glow", display: "Zen Maru Gothic", sans: "Mulish", body: "Mulish", script: "Comforter Brush", themes: ["beauty-fashion"], mood: ["soft"] },
  { id: "unbounded-aura", name: "Unbounded Aura", display: "Unbounded", sans: "Manrope", body: "Manrope", script: "Caveat", themes: ["beauty-fashion"], mood: ["pop"] },
  { id: "semi-cond-look", name: "Semi Condensed Look", display: "Sofia Sans Semi Condensed", sans: "Inter Tight", body: "Inter Tight", script: "Bad Script", themes: ["beauty-fashion", "tattoo"], mood: ["modern"] },
  { id: "ubuntu-cond-look", name: "Ubuntu Cond Lookbook", display: "Ubuntu Condensed", sans: "Golos Text", body: "Golos Text", script: "Caveat", themes: ["beauty-fashion", "blog-info"], mood: ["modern"] },
  { id: "playfair-caption", name: "Playfair Caption", display: "Playfair", sans: "PT Sans Caption", body: "PT Sans Caption", script: "Marck Script", themes: ["beauty-fashion", "home-decor"], mood: ["editorial"] },
  { id: "balsamiq-steps", name: "Balsamiq Steps", display: "Balsamiq Sans", sans: "Rubik", body: "Rubik", script: "Pangolin", themes: ["beauty-fashion", "blog-info", "food"], mood: ["friendly"] },
  { id: "golos-steps", name: "Golos Steps", display: "Golos Text", sans: "Golos Text", body: "Golos Text", script: "Neucha", themes: ["beauty-fashion", "blog-info"], mood: ["clean"] },
  { id: "montalt-steps", name: "Mont Alt Steps", display: "Montserrat Alternates", sans: "Mulish", body: "Mulish", script: "Caveat", themes: ["beauty-fashion"], mood: ["friendly"] },
  { id: "oswald-ba", name: "Oswald Before After", display: "Oswald", sans: "Inter Tight", body: "Inter Tight", script: "Caveat", themes: ["home-decor", "blog-info"], mood: ["bold"] },
  { id: "semi-cond-reno", name: "Semi Cond Renovation", display: "Sofia Sans Semi Condensed", sans: "Onest", body: "Onest", script: "Neucha", themes: ["home-decor"], mood: ["bold"] },
  { id: "roboto-cond-reno", name: "Roboto Cond Reno", display: "Roboto Condensed", sans: "Roboto", body: "Roboto", script: "Pangolin", themes: ["home-decor", "blog-info"], mood: ["clean"] },
  { id: "jura-blueprint", name: "Jura Blueprint", display: "Jura", sans: "Fira Code", body: "Fira Code", script: "Neucha", themes: ["home-decor", "blog-info"], mood: ["technical"] },
  { id: "handjet-plan", name: "Handjet Plan", display: "Handjet", sans: "PT Mono", body: "PT Mono", script: "Pangolin", themes: ["home-decor"], mood: ["technical"] },
  { id: "advent-drafting", name: "Advent Drafting", display: "Advent Pro", sans: "Martian Mono", body: "Overpass", script: "Bad Script", themes: ["home-decor"], mood: ["technical"] },
  { id: "gabriela-floral", name: "Gabriela Floral", display: "Gabriela", sans: "Bellota Text", body: "Bellota Text", script: "Great Vibes", themes: ["home-decor", "food"], mood: ["romantic"] },
  { id: "gentium-garden", name: "Gentium Garden", display: "Gentium Book Plus", sans: "Mulish", body: "Gentium Book Plus", script: "Marck Script", themes: ["home-decor"], mood: ["romantic"] },
  { id: "alice-floral", name: "Alice Floral", display: "Alice", sans: "Nunito Sans", body: "Alice", script: "Comforter", themes: ["home-decor", "beauty-fashion"], mood: ["romantic"] },
  { id: "messiri-riviera", name: "El Messiri Riviera", display: "El Messiri", sans: "Arsenal", body: "Arsenal", script: "Pattaya", themes: ["home-decor", "food"], mood: ["warm"] },
  { id: "alegreya-villa", name: "Alegreya Villa", display: "Alegreya SC", sans: "Alegreya Sans", body: "Alegreya", script: "Marck Script", themes: ["home-decor", "food"], mood: ["warm"] },
  { id: "yeseva-terrace", name: "Yeseva Terrace", display: "Yeseva One", sans: "Alegreya Sans SC", body: "Alegreya Sans", script: "Caveat", themes: ["home-decor"], mood: ["warm"] },
  { id: "underdog-market", name: "Underdog Market", display: "Underdog", sans: "Scada", body: "Scada", script: "Neucha", themes: ["food"], mood: ["rustic"] },
  { id: "podkova-crate", name: "Podkova Crate", display: "Podkova", sans: "PT Sans Narrow", body: "PT Serif", script: "Amatic SC", themes: ["food"], mood: ["rustic"] },
  { id: "distressed-farm", name: "Distressed Farm", display: "Rubik Distressed", sans: "Roboto Slab", body: "Roboto Slab", script: "Pangolin", themes: ["food", "tattoo"], mood: ["rustic"] },
  { id: "scribble-chalk", name: "Scribble Chalk", display: "Rubik Scribble", sans: "Balsamiq Sans", body: "Balsamiq Sans", script: "Neucha", themes: ["food"], mood: ["chalk"] },
  { id: "kelly-chalk", name: "Kelly Chalk", display: "Kelly Slab", sans: "Cuprum", body: "Cuprum", script: "Amatic SC", themes: ["food"], mood: ["chalk"] },
  { id: "oranien-chalk", name: "Oranienbaum Chalk", display: "Oranienbaum", sans: "Bellota Text", body: "Bellota Text", script: "Neucha", themes: ["food"], mood: ["chalk"] },
  { id: "nunito-fit", name: "Nunito Fit", display: "Nunito", sans: "Nunito Sans", body: "Nunito Sans", script: "Caveat", themes: ["food", "blog-info"], mood: ["clean"] },
  { id: "comfortaa-bowl", name: "Comfortaa Bowl", display: "Comfortaa", sans: "Mulish", body: "Mulish", script: "Pangolin", themes: ["food"], mood: ["soft"] },
  { id: "manrope-macro", name: "Manrope Macro", display: "Manrope", sans: "Manrope", body: "Manrope", script: "Neucha", themes: ["food", "blog-info"], mood: ["clean"] },
  { id: "doodle-diner", name: "Doodle Diner", display: "Rubik Doodle Shadow", sans: "Rubik", body: "Rubik", script: "Lobster", themes: ["food"], mood: ["retro"] },
  { id: "prosto-diner", name: "Prosto Diner", display: "Prosto One", sans: "Ubuntu Condensed", body: "Ubuntu", script: "Pacifico", themes: ["food", "blog-info"], mood: ["retro"] },
  { id: "kablammo-soda", name: "Kablammo Soda", display: "Kablammo", sans: "Balsamiq Sans", body: "Balsamiq Sans", script: "Pattaya", themes: ["food"], mood: ["retro"] },
  { id: "vinyl-jukebox", name: "Vinyl Jukebox", display: "Rubik Vinyl", sans: "Rubik", body: "Rubik", script: "Lobster", themes: ["food"], mood: ["retro"] },
  { id: "bubbles-drinks", name: "Bubbles Drinks", display: "Rubik Bubbles", sans: "Nunito", body: "Nunito", script: "Pacifico", themes: ["food"], mood: ["playful"] },
  { id: "yuji-irezumi", name: "Yuji Irezumi", display: "Yuji Syuku", sans: "Zen Maru Gothic", body: "Zen Maru Gothic", script: "Bad Script", themes: ["tattoo"], mood: ["oriental"] },
  { id: "kaisei-wave", name: "Kaisei Wave", display: "Kaisei Tokumin", sans: "Sofia Sans Condensed", body: "Sofia Sans", script: "Marck Script", themes: ["tattoo", "home-decor"], mood: ["oriental"] },
  { id: "reggae-koi", name: "Reggae Koi", display: "Reggae One", sans: "Onest", body: "Onest", script: "Caveat", themes: ["tattoo"], mood: ["oriental"] },
  { id: "ruslan-lettering", name: "Ruslan Lettering", display: "Ruslan Display", sans: "PT Sans Narrow", body: "PT Serif", script: "Great Vibes", themes: ["tattoo"], mood: ["heritage"] },
  { id: "oldstd-script", name: "Old Standard Script", display: "Old Standard TT", sans: "Sofia Sans Condensed", body: "Old Standard TT", script: "Comforter", themes: ["tattoo"], mood: ["heritage"] },
  { id: "playfair-sc-letter", name: "Playfair SC Letter", display: "Playfair Display SC", sans: "Jost", body: "Cormorant Garamond", script: "Great Vibes", themes: ["tattoo", "beauty-fashion"], mood: ["heritage"] },
  { id: "inter-catalog", name: "Inter Catalog", display: "Inter Tight", sans: "Inter", body: "Inter", script: "Bad Script", themes: ["tattoo", "blog-info"], mood: ["clean"] },
  { id: "golos-caption", name: "Golos Caption", display: "Golos Text", sans: "PT Sans Caption", body: "PT Sans Caption", script: "Caveat", themes: ["tattoo"], mood: ["clean"] },
  { id: "ubuntu-index", name: "Ubuntu Index", display: "Ubuntu Condensed", sans: "Ubuntu Mono", body: "Ubuntu", script: "Neucha", themes: ["tattoo", "blog-info"], mood: ["technical"] },
  { id: "vollkorn-tarot", name: "Vollkorn Tarot", display: "Vollkorn SC", sans: "Jost", body: "Vollkorn", script: "Great Vibes", themes: ["tattoo", "beauty-fashion"], mood: ["mystic"] },
  { id: "unicase-moon", name: "Unicase Moon", display: "Cormorant Unicase", sans: "Didact Gothic", body: "Cormorant Garamond", script: "Comforter", themes: ["tattoo"], mood: ["mystic"] },
  { id: "philosopher-star", name: "Philosopher Star", display: "Philosopher", sans: "Arsenal", body: "Arsenal", script: "Marck Script", themes: ["tattoo", "blog-info"], mood: ["mystic"] },
  { id: "glitch-grunge", name: "Glitch Grunge", display: "Rubik Glitch", sans: "Roboto Condensed", body: "Roboto", script: "Bad Script", themes: ["tattoo"], mood: ["grunge"] },
  { id: "burned-ink", name: "Burned Ink", display: "Rubik Burned", sans: "PT Sans Narrow", body: "PT Sans Narrow", script: "Neucha", themes: ["tattoo"], mood: ["grunge"] },
  { id: "train-poster", name: "Train Poster", display: "Train One", sans: "Onest", body: "Onest", script: "Caveat", themes: ["tattoo", "blog-info"], mood: ["bold"] },
  { id: "rubik-info", name: "Rubik Infographic", display: "Rubik", sans: "Rubik", body: "Rubik", script: "Caveat", themes: ["blog-info"], mood: ["clean"] },
  { id: "days-steps", name: "Days One Steps", display: "Days One", sans: "Golos Text", body: "Golos Text", script: "Neucha", themes: ["blog-info"], mood: ["bold"] },
  { id: "pixel-howto", name: "Pixel How-To", display: "Pixelify Sans", sans: "Inter", body: "Inter", script: "Pangolin", themes: ["blog-info"], mood: ["geek"] },
  { id: "bellota-calm", name: "Bellota Calm", display: "Bellota", sans: "Bellota Text", body: "Bellota Text", script: "Marck Script", themes: ["blog-info", "beauty-fashion"], mood: ["soft"] },
  { id: "gabriela-wellness", name: "Gabriela Wellness", display: "Gabriela", sans: "Mulish", body: "Mulish", script: "Comforter", themes: ["blog-info"], mood: ["soft"] },
  { id: "philosopher-mind", name: "Philosopher Mind", display: "Philosopher", sans: "Nunito Sans", body: "Nunito Sans", script: "Bad Script", themes: ["blog-info"], mood: ["soft"] },
  { id: "tinos-ledger", name: "Tinos Ledger", display: "Tinos", sans: "Ubuntu Mono", body: "PT Serif Caption", script: "Bad Script", themes: ["blog-info"], mood: ["finance"] },
  { id: "slab-ledger", name: "Slab Ledger", display: "Roboto Slab", sans: "IBM Plex Mono", body: "IBM Plex Sans", script: "Neucha", themes: ["blog-info"], mood: ["finance"] },
  { id: "semi-cond-money", name: "Semi Cond Money", display: "Sofia Sans Semi Condensed", sans: "Fira Code", body: "Onest", script: "Caveat", themes: ["blog-info"], mood: ["finance"] },
  { id: "prosto-postcard", name: "Prosto Postcard", display: "Prosto One", sans: "PT Sans Narrow", body: "PT Serif", script: "Pacifico", themes: ["blog-info"], mood: ["travel"] },
  { id: "charis-journal", name: "Charis Journal", display: "Charis SIL", sans: "Ubuntu Condensed", body: "Charis SIL", script: "Comforter Brush", themes: ["blog-info", "home-decor"], mood: ["travel"] },
  { id: "alegreya-route", name: "Alegreya Route", display: "Alegreya SC", sans: "Alegreya Sans SC", body: "Alegreya", script: "Caveat Brush", themes: ["blog-info"], mood: ["travel"] },
];
